-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 18:56:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TASKME
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TASKME
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TASKME` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `TASKME` ;

-- -----------------------------------------------------
-- Table `TASKME`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`equipes` (
  `idequipes` INT NOT NULL,
  `nomequipe` VARCHAR(45) NULL,
  `datecreation` DATETIME NULL,
  PRIMARY KEY (`idequipes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`utilisateurs` (
  `idutilisateurs` INT NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(125) NULL,
  `motdepasse` VARCHAR(45) NULL,
  `photo` VARCHAR(255) NULL,
  `equipes_idequipes` INT NOT NULL,
  `datecreation` DATETIME NULL,
  `datemodification` DATETIME NULL,
  PRIMARY KEY (`idutilisateurs`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
  INDEX `fk_utilisateurs_equipes1_idx` (`equipes_idequipes` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateurs_equipes1`
    FOREIGN KEY (`equipes_idequipes`)
    REFERENCES `TASKME`.`equipes` (`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`status` (
  `idstatus` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idstatus`),
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`entreprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`entreprises` (
  `identreprises` INT NOT NULL,
  `nomentreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`identreprises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`projets` (
  `idprojets` INT NOT NULL,
  `nomtache` VARCHAR(45) NULL,
  `datedebut` DATETIME NULL,
  `datefin` DATETIME NULL,
  `datemodification` DATETIME NULL,
  `description` VARCHAR(280) NULL,
  `utilisateurs_idutilisateurs` INT NOT NULL,
  `entreprises_identreprises` INT NOT NULL,
  `status_idstatus` INT NOT NULL,
  PRIMARY KEY (`idprojets`, `utilisateurs_idutilisateurs`, `entreprises_identreprises`, `status_idstatus`),
  INDEX `fk_taches_utilisateurs_idx` (`utilisateurs_idutilisateurs` ASC) VISIBLE,
  INDEX `fk_taches_entreprises1_idx` (`entreprises_identreprises` ASC) VISIBLE,
  INDEX `fk_taches_status1_idx` (`status_idstatus` ASC) VISIBLE,
  CONSTRAINT `fk_taches_utilisateurs`
    FOREIGN KEY (`utilisateurs_idutilisateurs`)
    REFERENCES `TASKME`.`utilisateurs` (`idutilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taches_entreprises1`
    FOREIGN KEY (`entreprises_identreprises`)
    REFERENCES `TASKME`.`entreprises` (`identreprises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taches_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `TASKME`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`priorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`priorites` (
  `idpriorites` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idpriorites`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`taches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`taches` (
  `idtaches` INT NOT NULL,
  `nomaction` VARCHAR(45) NULL,
  `datedebut` DATETIME NULL,
  `datefin` DATETIME NULL,
  `datemodification` DATETIME NULL,
  `description` VARCHAR(280) NULL,
  `projets_idprojets` INT NOT NULL,
  `priorites_idpriorites` INT NOT NULL,
  PRIMARY KEY (`idtaches`, `projets_idprojets`, `priorites_idpriorites`),
  INDEX `fk_taches_projets1_idx` (`projets_idprojets` ASC) VISIBLE,
  INDEX `fk_taches_priorites1_idx` (`priorites_idpriorites` ASC) VISIBLE,
  CONSTRAINT `fk_taches_projets1`
    FOREIGN KEY (`projets_idprojets`)
    REFERENCES `TASKME`.`projets` (`idprojets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taches_priorites1`
    FOREIGN KEY (`priorites_idpriorites`)
    REFERENCES `TASKME`.`priorites` (`idpriorites`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`projets_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`projets_equipes` (
  `taches_idtaches` INT NOT NULL,
  `taches_utilisateurs_idutilisateurs` INT NOT NULL,
  `taches_entreprises_identreprises` INT NOT NULL,
  `equipes_idequipes` INT NOT NULL,
  PRIMARY KEY (`taches_idtaches`, `taches_utilisateurs_idutilisateurs`, `taches_entreprises_identreprises`, `equipes_idequipes`),
  INDEX `fk_taches_has_equipes_equipes1_idx` (`equipes_idequipes` ASC) VISIBLE,
  INDEX `fk_taches_has_equipes_taches1_idx` (`taches_idtaches` ASC, `taches_utilisateurs_idutilisateurs` ASC, `taches_entreprises_identreprises` ASC) VISIBLE,
  CONSTRAINT `fk_taches_has_equipes_taches1`
    FOREIGN KEY (`taches_idtaches` , `taches_utilisateurs_idutilisateurs` , `taches_entreprises_identreprises`)
    REFERENCES `TASKME`.`projets` (`idprojets` , `utilisateurs_idutilisateurs` , `entreprises_identreprises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taches_has_equipes_equipes1`
    FOREIGN KEY (`equipes_idequipes`)
    REFERENCES `TASKME`.`equipes` (`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`entreprises_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`entreprises_equipes` (
  `entreprises_identreprises` INT NOT NULL,
  `equipes_idequipes` INT NOT NULL,
  PRIMARY KEY (`entreprises_identreprises`, `equipes_idequipes`),
  INDEX `fk_entreprises_has_equipes_equipes1_idx` (`equipes_idequipes` ASC) VISIBLE,
  INDEX `fk_entreprises_has_equipes_entreprises1_idx` (`entreprises_identreprises` ASC) VISIBLE,
  CONSTRAINT `fk_entreprises_has_equipes_entreprises1`
    FOREIGN KEY (`entreprises_identreprises`)
    REFERENCES `TASKME`.`entreprises` (`identreprises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entreprises_has_equipes_equipes1`
    FOREIGN KEY (`equipes_idequipes`)
    REFERENCES `TASKME`.`equipes` (`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TASKME`.`pwd_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASKME`.`pwd_reset` (
  `mail` VARCHAR(125) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Table `TASKME`.`roles`
-- -----------------------------------------------------

CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `libelle` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci